### ISSUE TITLE
Problems with linking to wiringPI

### ISSUE THREAD

**Issue by rkaczorek** [threebrooks/AdafruitStepperMotorHAT_CPP#1]
Hi
Thanks for porting the lib to C++ I'm planning to use it for telescope focuser project but I have very basic problem. Whatever I do I cannot link it to wiringPi library (installed with apt-get).

user@host:~/DEV/AdafruitStepperMotorHAT_CPP$ make
g++ -std=c++11 -c *.cpp
ar cr AdafruitStepperMotorHAT.a Adafruit_MotorHAT.o PWM.o
g++ -std=c++11 -o StepperMotorTest -lwiringPi StepperMotorTest.cpp AdafruitStepperMotorHAT.a
AdafruitStepperMotorHAT.a(PWM.o): In function `initPWM(int)':
PWM.cpp:(.text+0xa): undefined reference to `wiringPiI2CSetup'
PWM.cpp:(.text+0x32): undefined reference to `wiringPiI2CWriteReg8'
PWM.cpp:(.text+0x46): undefined reference to `wiringPiI2CWriteReg8'
PWM.cpp:(.text+0x58): undefined reference to `wiringPiI2CReadReg8'
PWM.cpp:(.text+0x78): undefined reference to `wiringPiI2CWriteReg8'
AdafruitStepperMotorHAT.a(PWM.o): In function `setPWMFreq(int)':
PWM.cpp:(.text+0x108): undefined reference to `wiringPiI2CReadReg8'
PWM.cpp:(.text+0x12c): undefined reference to `wiringPiI2CWriteReg8'
PWM.cpp:(.text+0x15c): undefined reference to `wiringPiI2CWriteReg8'
PWM.cpp:(.text+0x170): undefined reference to `wiringPiI2CWriteReg8'
PWM.cpp:(.text+0x188): undefined reference to `wiringPiI2CWriteReg8'
AdafruitStepperMotorHAT.a(PWM.o): In function `setPWM(int, int, int)':
PWM.cpp:(.text+0x1ba): undefined reference to `wiringPiI2CWriteReg8'
AdafruitStepperMotorHAT.a(PWM.o):PWM.cpp:(.text+0x1d4): more undefined references to `wiringPiI2CWriteReg8' follow
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by threebrooks** [comment]
A quick google suggests you need to have libi2c-dev installed. Can you try

sudo apt-get install libi2c-dev

and see whether that fixes it?

**Comment by rkaczorek** [comment]
I already tried this. It does not fix it. I'm trying to build it on ubuntu mate 16.04 running on raspberry pi 3. What's your config?

**Comment by threebrooks** [comment]
I am building it on NOOBs. This looks like an issue with Ubuntu Mate I think, because there's really nothing special in the g++ call.

**Comment by rkaczorek** [comment]
Indeed. It should be straight forward but for some reason it's not. I cannot figure out why because all libs are in place. I will try to build it on NOOBs then.

**Comment by rkaczorek** [comment]
I have nailed it down. Apparently Makefile needs some improvements (order of linking issue).
The line:
g++ -std=c++11 -o StepperMotorTest -lwiringPi StepperMotorTest.cpp AdafruitStepperMotorHAT.a
should be changed to:
g++ -std=c++11 -o StepperMotorTest StepperMotorTest.cpp AdafruitStepperMotorHAT.a -lwiringPi

Moreover for the latest and official (!) wiringPi you need to link additional libraries so the line should be:
g++ -std=c++11 -o StepperMotorTest StepperMotorTest.cpp AdafruitStepperMotorHAT.a -lwiringPi -lpthread -lcrypt -lrt

Note: You need latest and official wiringPi (not a binary version already installed on your system) for Raspberry Pi 3. Otherwise you will get the hardware issue:

`Unable to determine hardware version. I see: Hardware : BCM2835 
expecting BCM2708 or BCM2709.`

which is described [here](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=182191) and [here](https://github.com/Pi4J/pi4j/issues/319).

Can you test it on your side? I can send you a pull request if this works well.

**Comment by threebrooks** [comment]
I won't be able to test this for a few days, but you might as well do the pull request, since the change looks good either way.
