### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gaborszita** [threebrooks/AdafruitStepperMotorHAT_CPP#4]
Can please provide a license? Since this code has no license, I actually have no right to use it. I know its a small issue... but please, provide one. I just want to use this library in my project (yes, it is open source) and it would be better if you could provide a license.

**Comment by threebrooks** [comment]
Hi there, I just added the LICENSE file, it's the MIT license.

**Comment by gaborszita** [comment]
Thanks :)
