### ISSUE TITLE
WiringPi deprecated

### ISSUE THREAD

**Issue by gaborszita** [threebrooks/AdafruitStepperMotorHAT_CPP#8]
In August 2019, Gordon, the maintainer of WiringPi, announced that the [library will be deprecated](http://wiringpi.com/wiringpi-deprecated/). This caused issues for many projects using WiringPi, because it is not good for a project to use a deprecated library. Some decided to move over to PIGPIO, like [pi4j](https://github.com/Pi4J/pi4j/issues/467).
This library is also using WiringPi, which for the reasons described above is not very good. I think this project should also transition over to PIGPIO. I'd happy to hear your opinion about this and decide the further development of this project.
I'd be happy to help in this transition, or, perhaps even do the whole thing on my own.

**Comment by threebrooks** [comment]
I actually have not looked at this project in quite some time. I think in the interest of support, maybe it is better if you could create a fork that ports it to PIGPIO. When you have something working, I could then mark my project deprecated and I'll point to your in the README.

**Comment by gaborszita** [comment]
Okay, thanks. I think I will do that. Updates will go in this thread.

Closing
